<?php

namespace Bump\Lang\Tests;

use Bump\Core\CMS;
use Bump\Lang\Ru;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-21 at 11:54:30.
 */
class RuTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Ru
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $lang = 'ru';
        CMS::Session()->getInstance()->setItem('lang', $lang);
        Ru::setLang($lang);
        $this->object = Ru::getInstance();
    }


    public function testRussianTranslation()
    {
        $this->assertEquals($this->object->welcome, 'Добро пожаловать в ');
        $this->assertNotEquals($this->object->welcome, 'Ошибочный текст');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
