<?php

namespace Bump\Modules\FormFields\Tests;

use Bump\Modules\FormFields\FormFields;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 14:21:41.
 */
class FormFieldsTest extends \Bump\Tests\BaseTest
{
    /**
     * @var FormFields
     */
    protected $object;

    public static function setUpBeforeClass()
    {
        self::$fixtures = [
            '\\Bump\\Modules\\Forms\\Tests\\Fixtures\\FormsFixture',
            '\\Bump\\Modules\\FormFields\\Tests\\Fixtures\\FormFieldsFixture',
        ];
        parent::setUpBeforeClass();
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormFields;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\FormFields\FormFields::init
     */
    public function testInit()
    {
        $this->object->init();
        $this->assertInstanceOf('\Bump\Modules\FormFields\Model\FormField', $this->object->model);
    }

    /**
     * @covers Bump\Modules\FormFields\FormFields::getFields
     */
    public function testGetFields()
    {
        $fields = $this->object->getFields();
        $this->assertTrue(count($fields) > 0);
    }

    /**
     * @covers Bump\Modules\FormFields\FormFields::getTypes
     */
    public function testGetTypes()
    {
        $types = $this->object->getTypes();
        $this->assertTrue(count($types) > 0);
    }

    /**
     * @covers Bump\Modules\FormFields\FormFields::getTypesLabels
     */
    public function testGetTypesLabels()
    {
        $labels = $this->object->getTypesLabels();
        $this->assertTrue(count($labels) > 0);
    }
}
