<?php

namespace Bump\Modules\OEmbed\Tests;

use Bump\Modules\OEmbed\OEmbed;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 14:21:41.
 */
class OEmbedTest extends \Bump\Tests\BaseTest
{
    /**
     * @var OEmbed
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OEmbed;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\OEmbed\OEmbed::init
     */
    public function testInit()
    {
        $this->object->init();
    }

    /**
     * @covers Bump\Modules\OEmbed\OEmbed::getInfo
     */
    public function testCacheGetInfo()
    {
        \Bump\Core\CMS::Config()->request['path'] = 'https://www.youtube.com/watch?v=YE7VzlLtp-4';
        $this->setProperty('settings', ['cache' => 'true']);
        $res = $this->object->getInfo();
        $this->assertTrue(is_array($res['data']));
        $this->assertEquals($res['data']['title'], 'Big Buck Bunny');
    }

    /**
     * @covers Bump\Modules\OEmbed\OEmbed::getInfo
     */
    public function testNocahceGetInfo()
    {
        \Bump\Core\CMS::Config()->request['path'] = 'https://www.youtube.com/watch?v=YE7VzlLtp-4';
        $this->setProperty('settings', ['cache' => 'false']);
        $res = $this->object->getInfo();
        $this->assertTrue(is_array($res['data']));
        $this->assertEquals($res['data']['title'], 'Big Buck Bunny');
    }

    /**
     * @covers Bump\Modules\OEmbed\OEmbed::getInfo
     */
    public function testIncorrectGetInfo()
    {
        \Bump\Core\CMS::Config()->request['path'] = 'https://www.youtube.com/watch?v=non-existent-video-id';
        $res = $this->object->getInfo();
        $this->assertTrue(isset($res['success']));
        $this->assertFalse($res['success']);
    }
}
