<?php

namespace Bump\Core\Tests;

use Bump\Core\CMS;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-25 at 13:43:44.
 */
class CMSTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Bump\Core\CMS::Request
     */
    public function testRequest()
    {
        $request = CMS::Request();
        $this->assertInstanceOf('Bump\Core\Request', $request);
        $this->assertTrue($request === CMS::Request());
    }

    /**
     * @covers Bump\Core\CMS::User
     */
    public function testUser()
    {
        $user = CMS::User();
        $this->assertInstanceOf('Bump\Core\User', $user);
        $this->assertTrue($user === CMS::User());
    }

    /**
     * @covers Bump\Core\CMS::Session
     */
    public function testSession()
    {
        $session = CMS::Session();
        $this->assertInstanceOf('Bump\Core\Session', $session);
        $this->assertTrue($session === CMS::Session());
    }

    /**
     * @covers Bump\Core\CMS::Labels
     */
    public function testLabels()
    {
        $labels = CMS::Labels();
        $this->assertInstanceOf('Bump\Core\Labels', $labels);
        $this->assertTrue($labels === CMS::Labels());
    }

    /**
     * @covers Bump\Core\CMS::Config
     */
    public function testConfig()
    {
        $config = CMS::Config();
        $this->assertInstanceOf('Bump\Core\Configuration', $config);
        $this->assertTrue($config === CMS::Config());
    }

    /**
     * @covers Bump\Core\CMS::getLang
     */
    public function testGetLang()
    {
        $lang = CMS::getLang();
        $this->assertTrue(in_array($lang, ['En', 'Ru']));
    }

}
