<?php

namespace Bump\Core\Tests;

use Bump\Core\Configuration;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-26 at 09:20:58.
 */
class ConfigurationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Configuration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Configuration::getInstance();
    }

    /**
     * @covers Bump\Core\Configuration::init
     */
    public function testInit()
    {
        $this->object->init();
        $this->assertNotNull($this->object->db);
        $rows = $this->object->db->CacheGetAll(MAX_CACHE_TIME, "SELECT * FROM cms_configs");
        if ($rows) {
            foreach($rows as $row) {
                $this->assertObjectHasAttribute($row['name'], $this->object);
            }
        }
    }

    /**
     * @covers Bump\Core\Configuration::__get
     */
    public function test__get()
    {
        $this->assertEquals($this->object->__get('CODEPAGE'), "utf-8");
        $this->assertObjectNotHasAttribute('foo', $this->object);
        $this->assertObjectNotHasAttribute('bar', $this->object);
        $this->assertObjectNotHasAttribute('baz', $this->object);

        $this->assertEquals('', $this->object->foo);
        $this->assertEquals('', $this->object->bar);
        $this->assertEquals('', $this->object->baz);
    }
}
