<?php

namespace Bump\Core\Tests;

use Bump\Core\ExtStoreFilter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-27 at 13:10:36.
 */
class ExtStoreFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExtStoreFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExtStoreFilter();
    }

    /**
     * @covers Bump\Core\ExtStoreFilter::__construct
     */
    public function testDefaultVars()
    {
        $this->object = new ExtStoreFilter();
        $this->assertEquals($this->object->property, 'id');
        $this->assertEquals($this->object->operator, '=');
        $this->assertEquals($this->object->value, '');
        $this->assertEquals($this->object->type, 'numeric');
    }

    /**
     * @covers Bump\Core\ExtStoreFilter::setOperator
     */
    public function testSetOperator()
    {
        $this->object->setOperator('-');
        $this->assertEquals('-', $this->object->operator);
    }

    /**
     * @covers Bump\Core\ExtStoreFilter::setType
     */
    public function testSetType()
    {
        $this->object->setType('float');
        $this->assertEquals('float', $this->object->type);
    }

    /**
     * @covers Bump\Core\ExtStoreFilter::setValue
     */
    public function testSetValue()
    {
        $this->object->setValue('foobar');
        $this->assertEquals('foobar', $this->object->value);
    }

    /**
     * @covers Bump\Core\ExtStoreFilter::setProperty
     */
    public function testSetProperty()
    {
        $this->object->setProperty('test');
        $this->assertEquals('test', $this->object->property);
    }
}
