<?php

namespace Bump\Core\Tests;

use Bump\Core\Labels;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-26 at 14:37:01.
 */
class LabelsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Labels
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Labels::getInstance();
    }

    /**
     * @covers Bump\Core\Labels::getInstance
     */
    public function testGetInstance()
    {
        Labels::clear();
        $this->assertInstanceOf('Bump\Core\Labels', Labels::getInstance());
        $this->assertInstanceOf('Bump\Core\Labels', Labels::getInstance());
    }

    /**
     * @covers Bump\Core\Labels::getLabels
     */
    public function testGetLabels()
    {
        $this->assertTrue(is_array( $this->object->getLabels()));
    }

    public function testSetLang()
    {
        $this->object->setLang('ru');
        $this->assertInstanceOf('Bump\Lang\Ru', Labels::getInstance());

        $this->object->setLang('BAZ');
        $this->assertInstanceOf('Bump\Lang\En', Labels::getInstance());

        $this->object->setLang('en');
        $this->assertInstanceOf('Bump\Lang\En', Labels::getInstance());

        return Labels::getInstance();
    }

    /**
     * @covers Bump\Core\Labels::__get
     * @depends testSetLang
     */
    public function test__get($instance)
    {
        $this->assertEquals($instance->welcome, 'Welcome to ');
        $this->assertEquals($instance->foo, null);
    }

    public function testClear()
    {
        $this->assertNull(Labels::clear());
    }
}
