<?php

namespace Bump\Core\Tests;

use Bump\Core\Module;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-27 at 07:45:57.
 */
class ModuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Module
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new Module;
    }

    /**
     * @covers Bump\Core\Module::getModuleSettings
     */
    public function testGetModuleSettings()
    {
        $settings = $this->object->getModuleSettings('Bump\Modules\SysInfo\SysInfo');
        $this->assertEquals(['phpinfo', 'resolve'], array_keys($settings));
        $settings = $this->object->getModuleSettings('Bump\Modules\UserFiles\UserFiles');
        $this->assertEquals(['format'], array_keys($settings));
    }

    /**
     * @expectedException \ReflectionException
     */
    public function testWrongModule()
    {
        $this->object->getModuleSettings('Bump\Modules\Foo\Bar');
    }

    /**
     * @covers Bump\Core\Module::checkAccess
     */
    public function testCheckAccess()
    {
        $this->assertTrue(is_bool($this->object->checkAccess('Bump\Modules\Auth\Auth', 'auth')));
        $this->assertTrue(is_bool($this->object->checkAccess('Bump\Modules\SysInfo\SysInfo', 'getInfo')));
        $this->assertTrue(is_bool($this->object->checkAccess('Bump\Modules\EmailForms\EmailForms', 'sendForm')));
    }
}
