<?php

namespace Bump\Modules\SysInfo\Tests;

use Bump\Core\CMS;
use Bump\Modules\SysInfo\SysInfo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 14:21:41.
 */
class SysInfoTest extends \Bump\Tests\BaseTest
{
    /**
     * @var SysInfo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SysInfo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\SysInfo\SysInfo::init
     */
    public function testInit()
    {
        $this->object->init();
    }

    /**
     * @covers Bump\Modules\SysInfo\SysInfo::prepareData
     */
    public function testPrepareData()
    {
        $foo = $this->getMethod('prepareData');
        $foo->invokeArgs($this->object, []);
    }

    /**
     * @covers Bump\Modules\SysInfo\SysInfo::getInfo
     */
    public function testGetInfo()
    {
        $this->object->getInfo();
    }

}
