<?php

namespace Bump\Modules\EmailLogs\Tests;

use Bump\Modules\EmailLogs\EmailLogs;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 14:21:41.
 */
class EmailLogsTest extends \Bump\Tests\BaseTest
{
    /**
     * @var EmailLogs
     */
    protected $object;

    public static function setUpBeforeClass()
    {
        self::$fixtures = [
            '\\Bump\\Modules\\EmailLogs\\Tests\\Fixtures\\EmailLogsFixture',
        ];
        parent::setUpBeforeClass();
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EmailLogs;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\EmailLogs\EmailLogs::init
     */
    public function testInit()
    {
        $this->object->init();
        $this->assertInstanceOf('\Bump\Modules\EmailLogs\Model\EmailLog', $this->object->model);
    }

    /**
     * @covers Bump\Modules\EmailLogs\EmailLogs::_postGetRows
     */
    public function testPostGetRows()
    {
        $rows = $this->object->getRows();
        $this->assertTrue(count($rows)>0);
        $foo = $this->getMethod('_postGetRows');
        $foo->invokeArgs($this->object, [&$rows]);
        $this->assertTrue(htmlspecialchars(htmlspecialchars_decode($rows[0]['fl_address_to'])) === $rows[0]['fl_address_to']);
        $this->assertTrue(htmlspecialchars(htmlspecialchars_decode($rows[0]['fl_address_from'])) === $rows[0]['fl_address_from']);
    }
}
