<?php

namespace Bump\Modules\EmailAttachments\Tests;

use Bump\Core\CMS;
use Bump\Modules\EmailAttachments\EmailAttachments;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 14:21:41.
 */
class EmailAttachmentsTest extends \Bump\Tests\BaseTest
{
    /**
     * @var EmailAttachments
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EmailAttachments;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\EmailAttachments\EmailAttachments::init
     */
    public function testInit()
    {
        $this->object->init();
        $this->assertInstanceOf('\Bump\Modules\EmailAttachments\Model\EmailAttachment', $this->object->model);
    }

    /**
     * @covers Bump\Modules\EmailAttachments\EmailAttachments::addFile
     */
    public function testAddFile()
    {
        CMS::Config()->request = [
            'names' => json_encode(['test.txt']),
            'folder' => 'files',
            'form_id' => 0
        ];
        $res = $this->object->addFile();
        $this->assertTrue(isset($res['success']));
    }

    /**
     * @covers Bump\Modules\EmailAttachments\EmailAttachments::getFiles
     */
    public function testGetFiles()
    {
        $res = $this->object->getFiles([
            'form_id' => 0
        ]);
        $this->assertTrue(count($res)>0);
        $this->object->db->Execute('DELETE FROM cms_email_attachments WHERE form_id=0');
    }

    /**
     * @covers Bump\Modules\EmailAttachments\EmailAttachments::addFile
     */
    public function testAddFileException()
    {
        $this->expectedADOExceptionIn('Execute');
        $this->object->addFile();
    }

}
