<?php

namespace Bump\Modules\Albums\Tests;

use Bump\Core\CMS;
use Bump\Modules\Albums\Albums;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-22 at 13:27:07.
 */
class AlbumsTest extends \Bump\Tests\BaseTest
{
    /**
     * @var Albums
     */
    protected $object;

    public static function setUpBeforeClass()
    {
        self::$fixtures = [
            '\\Bump\\Modules\\Albums\\Tests\\Fixtures\\AlbumsFixture',
        ];
        parent::setUpBeforeClass();
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Albums;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\Albums\Albums::init
     * @covers Bump\Modules\Albums\Albums::getSettings
     */
    public function testInit()
    {
        $this->object->init();
        $this->assertInstanceOf('\Bump\Modules\Albums\Model\View', $this->object->view_model);
        $this->assertInstanceOf('\Bump\Modules\Albums\Model\Album', $this->object->model);
        $settings = $this->object->getSettings();
        $this->assertTrue(isset($settings['dnd']));
    }

    /**
     * @covers Bump\Modules\Albums\Albums::reorder
     */
    public function testReorder()
    {
        CMS::Config()->request['order'] = json_encode([
            1, 2
        ]);
        $res = $this->object->reorder();
        $this->assertTrue($res['success']);
    }

    /**
     * @covers Bump\Modules\Albums\Albums::_preSaveRow
     */
    public function testPreSaveRow()
    {
        $foo = $this->getMethod('_preSaveRow');
        $fields = [
            'c_title' => 'This - is : the test!',
            'c_slug' => ''
        ];
        $foo->invokeArgs($this->object, [&$fields]);
        $this->assertEquals($fields['c_slug'], 'this-is-the-test');
    }

    /**
     * @covers Bump\Modules\Albums\Albums::getAlbumsArray
     */
    public function testGetAlbumsArray()
    {
        $rows = $this->object->getAlbumsArray();
        $cnt1 = count($rows);
        $this->assertTrue($cnt1>0);
        $rows = $this->object->getAlbumsArray([
            'empty' => 1
        ]);
        $cnt2 = count($rows);
        $this->assertTrue(count($cnt2)>0);
        $this->assertTrue($cnt2>$cnt1);
    }

}
