<?php

namespace Bump\Modules\Settings\Tests;

use Bump\Modules\Settings\Settings;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 14:21:41.
 */
class SettingsTest extends \Bump\Tests\BaseTest
{
    /**
     * @var Settings
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Settings;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bump\Modules\Settings\Settings::init
     */
    public function testInit()
    {
        $this->object->init();
        $this->assertInstanceOf('\Bump\Modules\Settings\Model\Config', $this->object->model);
    }

    /**
     * @covers Bump\Modules\Settings\Settings::getRows
     * @covers Bump\Modules\Settings\Settings::_postSaveRow
     */
    public function testGetRows()
    {
        $rows = $this->object->getRows();
        $this->assertTrue(count($rows)>0);
        $foo = $this->getMethod('_postSaveRow');
        $foo->invokeArgs($this->object, []);
    }

}
